import { Component } from '@angular/core';
import { isNumber } from '@ng-bootstrap/ng-bootstrap/util/util';

@Component({
    selector: 'int-havamal',
    templateUrl: 'havamal.component.html',
    styleUrls: ['../app.component.css', "./havamal.component.css"]
})
export class HavamalComponent{
    special: string[] = ['Ǫ', 'ǫ', 'ǿ', 'Ǿ', 'ψ'];
    searchStanza: number = null;

    ON: string[] = [
        `Gáttir allar áðr gangi fram \n um skoðask skyli, \n um skyggnask skyli-- \n því at óvíst er at vita \n hvar óvinir \n sitja á fleti fyrir.`,
        `Gefendr heilir!\n Gestr er inn kominn,\n hvar skal sitja sjá?\n Mjǫk er bráðr\n sá er á brǫndum skal,\n síns um freista frama.`, 
        `Elds er þǫrf\n þeim's inn er kominn\n ok á kné kalinn.\n Matar ok váða\n er manni þǫrf,\n þeim er hefr um fjall farit.`,
        `Vatns er þǫrf\n þeim er til\n verðar kømr, þerru ok þjóðlaðar,\n góðs um ǿðis--\n ef sér geta mætti\n orðs ok endrþǫgu.`,
        `Vits er þǫrf\n þeim er víða ratar;\n dælt er heima hvat.\n At augabragði verðr\n sá er ekki kann\n ok með snotrum sitr.`,
        `At hygg jandi sinni\n skyli-t maðr hrǿsinn vera,\n heldr gætinn at geði,\n þá er horskr ok þǫgull\n kømr heimisgarða til.\n Sjaldan verðr víti vǫrum,\n því at óbrigðra vin\n fær ψ aldregi\n en mannvit mikit.`,
        `Inn vari gestr\n er til verðar kømr,\n þunnu hlóði þegir,\n eyrum hlýðir\n en augum skoðar--\n svá nýsisk fróðra hverr fyrir.`,
        `Hinn er sæll\n er sér um getr\n lof ok líknstafi.\n Ódælla er við þat\n er ψ eiga skal\n annars brjóstum í.`,
        `Sá er sæll\n er sjálfr um á\n lof ok vit meðan lifir.\n Því at ill ráð\n hefir ψ opt þegit\n annars brjóstum ór.`,
        `Byrði betri\n berr-at ψ brautu at\n en sé mannvit mikit.\n Auði betra\n þykkir þat í okunnum stað–\n slíkt er válaðs vera.`,
        `Byrði betri\n berr-at ψ brautu at\n en sé mannvit mikit.\n Vegnest verra\n vegr-a hann velli at\n en sé ofdrykkja ǫls.`,
        `Er-a svá gott\n sem gott kveða\n ǫl alda sonum.\n Því at færa veit\n er fleira drekkr,\n síns til geðs gumi.`,
        `Óminnishegri heitir\n sá er yfir ǫlðrum þrumir,\n hann stelr geði guma.\n Þess fugls fjǫðrum\n ek fjǫtraðr var’k\n í garði Gunnlaðar.`,
        `Ǫlr ek varð,\n varð ofrǫlvi,\n at ins fróða Fjalars.\n Því er ǫlðr bazt\n at aptr of heimtir\n hverr sitt geð gumi.`,
        `Þagalt ok hugalt\n skyli þjóðans barn,\n ok vígdjarft vera.\n Glaðr ok reifr\n skyli gumma hver,\n unz sinn bíðr bana.`,
        `Ósnjaller ψ\n hyggsk munu ey lifa\n ef hann við víg varask,\n en elli gefr\n honum engi frið,\n þótt honum geirar gefi.`,
        `Kópir afglapi\n er til kynnis kømr–\n þylsk hann um, eða þrumir.\n Allt er senn\n ef hann sylg um getr,\n uppi er þá geð guma.`,
        `Sá einn veit\n er víða ratar\n ok hefir fjǫlð um farit\n hverju geði\n stýrir gumna hverr.\n Sá er vitandi er vits.`,
        `Haldi-t ψ á keri,\n drekki þó at hófi mjǫð.\n Mæli þarft eða þegi.\n Ókynnis þess\n vár þik engi ψ\n at þú gangir snemma at sofa.`,
        `Gráðurgr halr,\n nema geðs viti,\n etr sér aldrtrega.\n opt fær hlǿgis\n er með horskum kømr\n manni heimskum magi.`,
        `Hjarðir þat vitu\n nær þær heim skulu\n ok ganga þá af grasi,\n en ósviðr ψ\n kann ævagi\n síns um mál maga.`,
        `Vesall ψ\n ok illa skapi\n hlær at hvívetna.\n Hittki hann veit\n er hann vita þyrfti:\n at hann er-at vamma vanr.`,
        `Ósviðr ψ\n vakir um allar nætr\n ok hyggr at hvívetna.\n Þá er móðr\n er at morni kømr,\n allt er víl sem var.`,
        `Ósnotr ψ\n hyggr sér alla vera\n viðlæ jendr vini.\n Hittki hann finnr,\n þótt er um hann fár lesi,\n ef hann með snotrum sitr.`,
        `Ósnotr ψ\n hyggr sér alla vera\n viðlæ jendr vini.\n Þá þat finnr,\n er at þingi kømr,\n at hann á formælendr fá.`,
        `Ósnotr ψ\n þikkisk allt vita\n ef hann á sér í vá veru.\n Hittki hann veit\n hvat hann skal við kveða,\n ef hans freista firar.`,
        `Ósnotr ψ\n er með aldir kømr,\n þat er bazt at hann þegi.\n Engi þat veit\n at hann ekki kann,\n nema hann mæli til mart.\n Veit-a ψ\n hinn er vætki veit\n þótt hann mæli til mart.`,
        `Fróðr sá þykkisk\n er fregna kann,\n ok segja it sama.\n Eyvitu leyna\n megu ýta synir\n því er gengr um guma.`,
        `Ǿrna mælir\n sá er æva þegir\n staðlausu stafi.\n Hraðmælt tunga,\n nema haldendr eigi,\n opt sér ógott um gelr.`,
        `At augabragði\n skal-a ψ annan hafa,\n þótt til kynnis komi.\n Margr þá fróðr þykkisk\n ef hann freginn er-at,\n ok nái hann þurrfjallr þruma.`,
        `Fróðr þykkisk\n sá er flátta tekr\n gestr at gest hæðinn.\n Veit-a gǫrla\n sá er um verði glissir,\n þótt hann með grǫnum glami.`,
        `Gumnar margir\n erusk gagnhollir,\n en at virði rekask.\n Aldar róg\n þat mun æ vera:\n órir gestr við gest.`,
        `Árlinga verðar\n skyli ψ opt fá\n nema til kynnis komi.\n Sitr ok snópir,\n lætr sem sólginn sé,\n ok kann fregna at fá.`,
        `Afhvarf mikit\n er til ills vinar,\n þótt á brautu búi.\n En til góðs vinar\n liggja gagnvegir,\n þótt hann sé firr farinn.`,
        `Ganga skal.\n Skal-a gestr vera\n ey í einum stað.\n Ljúfr verðr leiðr\n ef lengi stir\n annars fletjum á.`,
        `Bú er betra\n þótt lílit sé–\n halr er heima hver.\n Þótt tvær geitr eigi\n ok taugreptan sal,\n þat er þó betra en bǿn.`,
        `Bú er betra\n þótt lílit sé–\n halr er heima hver.\n Blóðugt er hjarta\n þeim er biðja skal\n sér í mál hvert matar.`,
        `Vápnum sínum\n skal-a ψ velli á\n feti ganga framarr;\n því at óvist er at vita\n nær verðr á vegum úti\n geirs um þǫrf guma.`,
        `Fann’k-a ek mildan mann\n eða svá matar góðan\n at ei væri þiggja þegit,\n eða síns fjár\n svá gjǫflan\n at leið sé laun ef þegi.`,
        `Fjár síns\n er fengit hefr\n skyli-t ψ þǫrf þola.\n Opt sparir leiðum\n þat’s hefir ljúfum hugat–\n mart gengr verr en varir`,
        `Vápnum ok váðum\n skulu vinir gleðjask;\n þat er á sjálfum sýnst.\n Viðrgefendr ok endrgefendr\n erusk lengst vinir\n ef þat bíðr at verða vel.`,
        `Vin sínum\n skal ψ vinr vera,\n ok gjalda gjǫf við gjǫf.\n Hlátr við hlátri\n skyli hǫlðar taka,\n en lausung við lygi.`,
        `Vín sínum\n skal ψ vinr vera,\n þeim ok þess vin,\n en óvinar síns\n skyli engi ψ\n vinar vinr vera.`,
        `Veiztu, ef þú vin átt,\n þann er þú vel trúir,\n ok vill þú af honum gott geta,\n geði skaltu við þann blanda,\n ok gjǫfum skipta,\n fara at finna opt.`,
        `Ef þú átt annan,\n þann's þú illa trúir,\n vildu af honum þó gott geta--\n fagrt skaltu við þann mæla\n en flátt hyggja,\n ok gjalda lausung við lygi.`,
        `Þat er enn of þann,\n er þú illa trúir,\n ok þér er grunt at hans geði:\n hlæja skaltu við þeim,\n ok um hug mæla,\n glík skulu gjǫld gjǫfum.`,
    ];

    NL: string[] = [
        `Bij iedere ingang \n voordat u binnenkomt, \n kijk om u heen, \n kijk goed om u heen, \n want u weet nooit waar uw vijanden zitten.`,
        `Heil aan de gastheer!\n Een gast is binnen gekomen,\n waar moet deze zitten?\n Hij is heel gretig,\n staande op de deurpost,\n klaar om zijn geluk te wagen.`,
        `Vuur is nodig \n voor hij die is binnen gekomen\n zijn knieën rillen.\n Hij heeft voedsel en droge kleren\n hard nodig,\n na zijn reis over de bergen.`,
        `Water is nodig\n voor hij die naar\n de maaltijd komt, drogen en een warm welkom,\n van een vriendelijke gastheer --\n en als hij het kan krijgen,\n woord en stilte.`,
        `Wijsheid is nodig\n voor hij die reist;\n Thuis is alles makkelijk;\n Hij zal worden uitgelachen\n als hij niets weet en bij de wijzen zit.`,
        `Een man zou niet moeten opscheppen\n over zijn wijsheid,\n liever bedachtzaam over zijn geest,\n wanneer hij stil en wijs\n naar het huis van een ander gaat.\n Zelden overkomt pijn een wijze,\n want hij heeft geen trouwere vriend\n dan grote wijsheid.`,
        `De attente gast\n die naar een maaltijd komt,\n is stil en luistert aandachtig,\n hij luistert met zijn oren\n hij kijkt met zijn ogen--\n Zo vinden de wijzen hun weg vooruit.`,
        `Hij die lof en verlichting\n vindt in zichzelf\n is gelukkig.\n Het is moeilijker\n voor hem om dat\n te hebben in andermans hart.`,
        `Diegene is gelukkig\n die voor zichzelf lof en wijsheid\n heeft tijdens het leven.\n Omdat slecht advies\n vaak ontvangen wordt door mensen\n uit andermans hart.`,
        `Byrði betri\n berr-at ψ brautu at\n en sé mannvit mikit.\n Auði betra\n þykkir þat í okunnum stað–\n slíkt er válaðs vera.`,
        `Een betere last\n kan niet gedragen worden\n door een man op reis dan grote wijsheid.\n Een slechtere voorziening\n kan hij niet meenemen\n dan te veel alcohol.`,
        `Alcohol is niet zo goed\n als ze zeggen dat het is\n voor de mensen.\n Omdat ze minder weten\n als ze meer drinken,\n en zijn minder meester van hun geest.`,
        `Vergeetvogel heet het\n wat over vliegt als men drinkt,\n hij steelt een mens' geest.\n De vogel zijn veren\n hebben mij gevangen\n toen ik in Gunnlaðar's huis was.`,
        `Ik werd dronken,\n ik werd te dronken,\n in Fjalar's huis.\n Ieder feestmaal is het best\n waar men zijn geest \n mee naar huis neemt.`,
        `Stil en attent\n moet de nobele zijn,\n evenals dapper.\n Dankbaar en vrolijk,\n zou ieder mens moeten zijn,\n tot op de dood.`,
        `Onwijze mensen\n denken dat ze altijd leven\n zolang ze nooit vechten,\n maar ouderdom geeft\n ze geen vrede,\n zelfs als wapens dat wel doen.`,
        `Een dwaas staart\n als hij naar een feestmaal komt--\n hij zegt te veel of zegt niets.\n Zodra hij een slok krijgt,\n zegt hij alles wat hij weet.`,
        `Alleen diegene\n die ver reist\n en veel rond geweest is\n weet wat voor geest iedere wijze man heeft.\n Diegene is wijs.`,
        `Laat men niet de beker vasthouden,\n maar laat hen met mate hun mede drinken.\n Laat ze wat goeds zeggen, of stil zijn.\n Voor de onbeleefdheid\n zal niemand het je kwalijk nemen\n als je eerder naar bed gaat.`,
        `Een gulzig mens,\n tenzij die zijn geest kent,\n eet zich een leven lang verdriet.\n Vaak wordt een dwaas\n vanwege zijn maag\n uitgelachen als die onder de wijzen komt.`,
        `Kuddes weten\n wanneer ze naar huis moeten\n en het gras moeten verlaten,\n maar een dwaas\n weet nooit\n de omvang van zijn maag.`,
        `Een dwaas\n met een slechte mentale vorm\n lacht overal om.\n Hij weet niet\n wat hij zou moeten weten:\n hij is niet perfect.`,
        `Een dwaas\n blijft de hele nacht\n denken aan zijn problemen.\n Hij is moe\n als de ochtend komt,\n en zijn problemen onopgelost.`,
        `Een onwijze man\n denkt dat iedereen\n die met hem lacht zijn vriend is.\n Hij begrijpt niet,\n dat ze hem belachelijk maken\n als hij bij de wijzen zit.`,
        `Een onwijze man\n denkt dat iedereen\n die met hem lacht zijn vriend is.\n Dan vindt hij,\n dat er maar weinig voor hem spreken\n als hij zich moet verdedigen.`,
        `Een onwijze man\n denkt dat hij alles weet\n zolang hij een schuilplaats heeft.\n Hij weet niet\n hoe hij moet reageren\n als men hem test.`,
        `Een onwijze man\n die bij anderen komt,\n kan beter zijn mond houden.\n Niemand zal weten\n dat hij niks weet,\n als hij niets zegt.\n Een man\n die niets weet,\n weet niet dat hij te veel praat.`,
        `Diegene lijkt wijs\n die vragen stelt,\n en kan beantwoorden.\n Mensen kunnen geen\n geheimen bewaren van\n wat ze over anderen horen.`,
        `Diegene die nooit stil is,\n spreekt veel \n betekenisloze woorden.\n Een snel gesproken tong,\n tenzij de eigenaar hem controleert,\n zingt vaak om problemen voor zichzelf.`,
        `Een man moet niet\n een ander uitlachen,\n ook niet een bezoeker.\n Velen lijken wijs\n als er geen vragen gesteld worden,\n terwijl die zelf ook niet beter weten.`,
        `Wijs lijkt\n diegene die een ander belachelijk maakt\n en een andere gast minacht.\n Hij weet niet veel\n diegene die grijnst tijdens een feest,\n ookal lacht hij met anderen.`,
        `Veel mensen\n zijn vriendelijk voor elkaar,\n maar vechten tijdens een feest.\n Mensen zullen altijd\n ruzie hebben:\n een gast vecht met een gast.`,
        `Een man moet\n vroeg zijn maatlijd eten,\n tenzij hij op bezoek gaat.\n Hij zit onderuitgezakt,\n doet alsof hij verhongerd,\n en praat over niks.`,
        `De weg is lang\n naar een slechte vriend,\n ookal woont die dichtbij.\n Echter, naar een goede vriend\n liggen snelwegen. \n Je bent er zo, ookal woont die ver weg.`,
        `Je moet in beweging blijven.\n Nooit te lang \n op dezelfde plek blijven.\n Een geliefde wordt een gehate\n als die te lang blijft\n op een anders vloer.`,
        `Beter om wel een huis te hebben\n ookal is het klein--\n iedereen moet een plek thuis kunnen noemen.\n Ookal heb je maar twee geiten\n onder een gammel dak,\n dat is beter dan bedelen.`,
        `Beter om wel een huis te hebben\n ookal is het klein--\n iedereen moet een plek thuis kunnen noemen.\n Het hart bloedt\n van hij die moet bedelen om ieder maal\n van iemand anders.`,
        `Zijn wapens\n moet een man buitenshuis\n dichtbij houden;\n want het is onzeker\n wanneer hij onderweg\n een speer nodig heeft.`,
        `Ik heb nooit een man ontmoet,\n zo gul noch gastvrij\n dat hij niets wilt ontvangen,\n of zo gul\n met zijn geld\n dat hij zijn loon zal haten.`,
        `Een man moet niet\n met zijn geld zo zuinig zijn\n dat hij niet aan zijn behoeften kan voldoen.\n Wat je spaart gaat vaak naar\n je vijanden in plaats van je geliefden--\n veel loopt vaak slechter dan je zou verwachten.`,
        `Met wapens en kleren\n moeten vrienden elkaar verblijden;\n dat is goed zichtbaar.\n Wederkerige gevers en ontvangers\n zijn langst vrienden\n als dat standhoudt, gaat het goed.`,
        `Voor een vriend\n zal een man een vriend zijn,\n en hij geeft een geschenk voor een geschenk.\n Men moet een\n lach met een lach nemen,\n maar leugens met een leugen.`,
        `Voor een vriend\n zal een man een vriend zijn,\n voor diegene en diegene's vriend,\n maar voor diegene's vijanden\n moet een man\n geen vriend zijn.`,
        `Weet je, als je een vriend hebt,\n die je goed vertrouwt,\n en wil je dat er goed komt van de vriendschap--\n spreek hem vaak,\n geef elkaar een gift,\n bezoek hem vaak.`,
        `Als je een vriend hebt,\n die je slecht vertrouwt,\n en je wil dat er goed van komt--\n Spreek dan vriendelijk,\n vlei hem,\n en betaal zijn verraad met je eigen.`,
        `Diezelfde mensen,\n die je slecht vertrouwt,\n en  zijn gedachten wantrouwt:\n met hen moet je lachen,\n en spreken over je gedachten,\n en alles gelijk terugbetalen.`,
    ];
}